version: "3.8"

services:
  messenger:
    build: .
    container_name: messenger_app
    volumes:
      - .:/app
      - /app/node_modules 
    ports:
      - "3000:3000" 
      - "5000:5000" 
      - "8000:8000" 
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb

  mongodb:
    image: mongo:8.0.5-rc2-noble
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
